[project]
name = "approval_center"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "discord-py>=2.7.1",
    "fastapi[standard]>=0.142.2",
    "pydantic>=2.13.5",
]

[project.scripts]
approval_center = "approval_center:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
